# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NicotineFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NicotineFood', models.CharField(default='Financial', max_length=100, verbose_name='SmokingMedium')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfSmoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SmokingMedium', models.CharField(default='Financial', max_length=100, verbose_name='SmokingMedium')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
