# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NicotineFoods',
            new_name='NicotineFood',
        ),
    ]
