# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0002_auto_20160716_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhysicalActivitySpeed', models.CharField(choices=[('Walking', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')]), ('Jogging', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nicotinefood',
            name='NicotineFood',
            field=models.CharField(default='Nicotine Bubble Gum', max_length=100, verbose_name='NicotineFood'),
        ),
        migrations.AlterField(
            model_name='typeofsmoke',
            name='SmokingMedium',
            field=models.CharField(default='Cigrate', max_length=100, verbose_name='SmokingMedium'),
        ),
    ]
