# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0004_auto_20160716_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietInTakePerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhichDrink', models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('AAA', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DietInTake',
        ),
    ]
