# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0005_auto_20160716_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietintakeperday',
            name='FatInTake',
            field=models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20),
        ),
        migrations.AddField(
            model_name='dietintakeperday',
            name='FoodSupliment',
            field=models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20),
        ),
        migrations.AlterField(
            model_name='dietintakeperday',
            name='WhichDrink',
            field=models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='PhysicalActivitySpeed',
            field=models.CharField(choices=[('Meditation', [('10 Min', '10 Min'), ('20 Min', '20 Min'), ('>20 Min', '>20 Min')]), ('Physical-Exercise', [('No', 'No'), ('Negligible', 'Negligible')]), ('Cycling', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')]), ('Dance', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')]), ('Yoga', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')]), ('Walking', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')]), ('Jogging-Running', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20),
        ),
    ]
