# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0015_auto_20160717_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurereading',
            name='User',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Full Name:'),
        ),
        migrations.AlterField(
            model_name='cholesterolreading',
            name='User',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Full Name:'),
        ),
        migrations.AlterField(
            model_name='dietintakeperday',
            name='User',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Full Name:'),
        ),
        migrations.AlterField(
            model_name='nicotinefood',
            name='User',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Full Name:'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='User',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Full Name:'),
        ),
        migrations.AlterField(
            model_name='typeofsmoke',
            name='User',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Full Name:'),
        ),
        migrations.AlterField(
            model_name='usermedicalprofile',
            name='User',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Full Name:'),
        ),
    ]
