# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0016_auto_20160717_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermedicalprofile',
            old_name='User',
            new_name='Subject',
        ),
        migrations.AlterField(
            model_name='nicotinefood',
            name='NicotineFood',
            field=models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='No', max_length=100, verbose_name='NicotineFood'),
        ),
        migrations.AlterField(
            model_name='typeofsmoke',
            name='SmokingMedium',
            field=models.CharField(default='Cigrate/Nicotine', max_length=100, verbose_name='SmokingMedium'),
        ),
    ]
