# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RiskGroups', models.CharField(choices=[('negligible', 'negligible'), ('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('certain', 'certain')], default='low', max_length=20)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DietScore', models.IntegerField(default=0, verbose_name='LifeStyleScore')),
                ('BloodPressureScore', models.IntegerField(default=0, verbose_name='LifeStyleScore')),
                ('CholesterolScore', models.IntegerField(default=0, verbose_name='LifeStyleScore')),
                ('PhysicalActivity', models.IntegerField(default=0, verbose_name='PhysicalActivity Score')),
                ('SmokeScore', models.IntegerField(default=0, verbose_name='Smoke Score')),
                ('TotalScore', models.IntegerField(default=0, verbose_name='TotalScore')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
                ('Outcome', models.OneToOneField(default='low', on_delete=django.db.models.deletion.CASCADE, to='fhirfront.RiskLabels', verbose_name='OutCome')),
                ('User', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Full Name:')),
            ],
        ),
    ]
