# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cholesterol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskcategory', models.CharField(blank=True, db_column='RiskCategory', max_length=300, null=True)),
                ('cholesterolreadings', models.CharField(blank=True, db_column='CholesterolReadings', max_length=300, null=True)),
                ('mean', models.CharField(blank=True, db_column='Mean', max_length=300, null=True)),
                ('firststandarddeviation', models.CharField(blank=True, db_column='FirstStandardDeviation', max_length=300, null=True)),
                ('firststandarddeviationscore', models.CharField(blank=True, db_column='FirstStandardDeviationScore', max_length=300, null=True)),
                ('secondstandarddeviation', models.CharField(blank=True, db_column='SecondStandardDeviation', max_length=300, null=True)),
                ('secondstandarddeviationscore', models.CharField(blank=True, db_column='SecondStandardDeviationScore', max_length=300, null=True)),
                ('thirdstandarddeviation', models.CharField(blank=True, db_column='ThirdStandardDeviation', max_length=300, null=True)),
                ('thirdstandarddeviationscore', models.CharField(blank=True, db_column='ThirdStandardDeviationScore', max_length=300, null=True)),
                ('documentation', models.CharField(blank=True, db_column='Documentation', max_length=300, null=True)),
            ],
            options={
                'db_table': 'cholesterol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agerisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroup', models.CharField(blank=True, db_column='AgeGroup', max_length=200, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=11, null=True)),
                ('weightrange', models.CharField(blank=True, db_column='WeightRange', max_length=200, null=True)),
                ('firststandarddeviation', models.FloatField(blank=True, db_column='FirstStandardDeviation', null=True)),
                ('firstscore', models.FloatField(blank=True, db_column='FirstScore', null=True)),
                ('secondstandarddeviation', models.FloatField(blank=True, db_column='SecondStandardDeviation', null=True)),
                ('secondscore', models.FloatField(blank=True, db_column='SecondScore', null=True)),
                ('thirdstandarddeviation', models.FloatField(blank=True, db_column='ThirdStandardDeviation', null=True)),
                ('documentation', models.CharField(blank=True, db_column='Documentation', max_length=300, null=True)),
            ],
            options={
                'db_table': 'agerisk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alcoholrisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=11, null=True)),
                ('frequencyofalcoholintake', models.CharField(blank=True, db_column='FrequencyofAlcoholinTake', max_length=200, null=True)),
                ('noofdrinksrange', models.CharField(blank=True, db_column='NoOfDrinksRange', max_length=200, null=True)),
                ('documentation', models.CharField(blank=True, db_column='Documentation', max_length=300, null=True)),
            ],
            options={
                'db_table': 'alcoholrisk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bloodpressurerisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskcategory', models.CharField(blank=True, db_column='RiskCategory', max_length=200, null=True)),
                ('systolicreading', models.CharField(blank=True, db_column='SystolicReading', max_length=200, null=True)),
                ('diastolicreading', models.CharField(blank=True, db_column='DiastolicReading', max_length=200, null=True)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
            ],
            options={
                'db_table': 'bloodpressurerisk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dietrisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hormonalcomplicationscategory', models.CharField(blank=True, db_column='HormonalComplicationsCategory', max_length=300, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=300, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=11, null=True)),
                ('agerange', models.CharField(blank=True, db_column='AgeRange', max_length=100, null=True)),
                ('mean', models.FloatField(blank=True, db_column='Mean', null=True)),
                ('firststandarddeviation', models.CharField(blank=True, db_column='FirstStandardDeviation', max_length=200, null=True)),
                ('firststandarddeviationscore', models.CharField(blank=True, db_column='FirstStandardDeviationScore', max_length=200, null=True)),
                ('secondstandarddeviation', models.CharField(blank=True, db_column='SecondStandardDeviation', max_length=200, null=True)),
                ('secondstandarddeviationscore', models.CharField(blank=True, db_column='SecondStandardDeviationScore', max_length=200, null=True)),
                ('thirdstandarddeviation', models.CharField(blank=True, db_column='ThirdStandardDeviation', max_length=200, null=True)),
                ('thirdstandarddeviationscore', models.CharField(blank=True, db_column='ThirdStandardDeviationScore', max_length=200, null=True)),
                ('documentation', models.CharField(blank=True, db_column='Documentation', max_length=300, null=True)),
            ],
            options={
                'db_table': 'dietrisk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hormonalrisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietcategory', models.CharField(blank=True, db_column='DietCategory', max_length=300, null=True)),
                ('noofpersons', models.CharField(blank=True, db_column='NoofPersons', max_length=300, null=True)),
                ('noofcalories', models.CharField(blank=True, db_column='NoOfCalories', max_length=300, null=True)),
                ('mean', models.CharField(blank=True, db_column='Mean', max_length=300, null=True)),
                ('firststandarddeviationscore', models.CharField(blank=True, db_column='FirstStandardDeviationScore', max_length=300, null=True)),
                ('secondstandarddeviation', models.CharField(blank=True, db_column='SecondStandardDeviation', max_length=300, null=True)),
                ('secondstandarddeviationscore', models.CharField(blank=True, db_column='SecondStandardDeviationScore', max_length=300, null=True)),
                ('thirdstandarddeviation', models.CharField(blank=True, db_column='ThirdStandardDeviation', max_length=300, null=True)),
                ('thirdstandarddeviationscore', models.CharField(blank=True, db_column='ThirdStandardDeviationScore', max_length=300, null=True)),
                ('documentation', models.CharField(blank=True, db_column='Documentation', max_length=300, null=True)),
            ],
            options={
                'db_table': 'hormonalrisk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Physicalactivityrisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physicalactivitycategory', models.CharField(blank=True, db_column='PhysicalActivityCategory', max_length=299, null=True)),
                ('agegroup', models.CharField(blank=True, db_column='AgeGroup', max_length=200, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=11, null=True)),
                ('weightrange', models.CharField(blank=True, db_column='WeightRange', max_length=200, null=True)),
                ('firststandarddeviation', models.FloatField(blank=True, db_column='FirstStandardDeviation', null=True)),
                ('firstscore', models.FloatField(blank=True, db_column='FirstScore', null=True)),
                ('secondstandarddeviation', models.FloatField(blank=True, db_column='SecondStandardDeviation', null=True)),
                ('secondscore', models.FloatField(blank=True, db_column='SecondScore', null=True)),
                ('thirdstandarddeviation', models.FloatField(blank=True, db_column='ThirdStandardDeviation', null=True)),
                ('documentation', models.CharField(blank=True, db_column='Documentation', max_length=300, null=True)),
            ],
            options={
                'db_table': 'physicalactivityrisk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexrisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroup', models.CharField(blank=True, db_column='AgeGroup', max_length=200, null=True)),
                ('categorysex', models.CharField(blank=True, db_column='CategorySex', max_length=11, null=True)),
                ('firststandarddeviation', models.FloatField(blank=True, db_column='FirstStandardDeviation', null=True)),
                ('firstscore', models.FloatField(blank=True, db_column='FirstScore', null=True)),
                ('secondstandarddeviation', models.FloatField(blank=True, db_column='SecondStandardDeviation', null=True)),
                ('secondscore', models.FloatField(blank=True, db_column='SecondScore', null=True)),
                ('thirdstandarddeviation', models.FloatField(blank=True, db_column='ThirdStandardDeviation', null=True)),
                ('documentation', models.CharField(blank=True, db_column='Documentation', max_length=300, null=True)),
            ],
            options={
                'db_table': 'sexrisk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Smokingrisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofcigarette', models.CharField(blank=True, db_column='NoOfCigarette', max_length=200, null=True)),
                ('frequency_time_slot', models.CharField(blank=True, db_column='Frequency-Time-Slot', max_length=300, null=True)),
                ('smokingtype', models.CharField(blank=True, db_column='SmokingType', max_length=7, null=True)),
                ('firststandarddeviation', models.FloatField(blank=True, db_column='FirstStandardDeviation', null=True)),
                ('firststandarddeviationscore', models.FloatField(blank=True, db_column='FirstStandardDeviationScore', null=True)),
                ('secondstandarddeviation', models.FloatField(blank=True, db_column='SecondStandardDeviation', null=True)),
                ('secondstandarddeviationscore', models.FloatField(blank=True, db_column='SecondStandardDeviationScore', null=True)),
                ('thirdstandarddeviation', models.FloatField(blank=True, db_column='ThirdStandardDeviation', null=True)),
                ('thirdstandarddeviationscore', models.FloatField(blank=True, db_column='ThirdStandardDeviationScore', null=True)),
            ],
            options={
                'db_table': 'smokingrisk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Weightrisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightcategory', models.CharField(blank=True, db_column='WeightCategory', max_length=200, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=11, null=True)),
                ('bmi', models.CharField(blank=True, db_column='BMI', max_length=200, null=True)),
                ('firststandarddeviation', models.FloatField(blank=True, db_column='FirstStandardDeviation', null=True)),
                ('firstscore', models.FloatField(blank=True, db_column='FirstScore', null=True)),
                ('secondstandarddeviation', models.FloatField(blank=True, db_column='SecondStandardDeviation', null=True)),
                ('secondscore', models.FloatField(blank=True, db_column='SecondScore', null=True)),
                ('thirdstandarddeviation', models.FloatField(blank=True, db_column='ThirdStandardDeviation', null=True)),
                ('documentation', models.CharField(blank=True, db_column='Documentation', max_length=300, null=True)),
            ],
            options={
                'db_table': 'weightrisk',
                'managed': True,
            },
        ),
    ]
