# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0003_auto_20160803_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerisk',
            name='thirdscore',
            field=models.FloatField(blank=True, db_column='Thirdscore', null=True),
        ),
    ]
