# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0006_auto_20160803_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurerisk',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Same', 'Same')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='dietrisk',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Same', 'Same')], default='Same', max_length=20),
        ),
        migrations.AlterField(
            model_name='smokingrisk',
            name='Sex',
            field=models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Passive', max_length=20),
        ),
    ]
