# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0007_auto_20160803_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietrisk',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dietrisk',
            name='agerange',
        ),
        migrations.RemoveField(
            model_name='dietrisk',
            name='firststandarddeviation',
        ),
        migrations.RemoveField(
            model_name='dietrisk',
            name='hormonalcomplicationscategory',
        ),
        migrations.RemoveField(
            model_name='hormonalrisk',
            name='dietcategory',
        ),
        migrations.RemoveField(
            model_name='hormonalrisk',
            name='noofcalories',
        ),
        migrations.RemoveField(
            model_name='hormonalrisk',
            name='noofpersons',
        ),
        migrations.AddField(
            model_name='dietrisk',
            name='dietcategory',
            field=models.CharField(blank=True, db_column='DietCategory', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietrisk',
            name='noofcalories',
            field=models.CharField(blank=True, db_column='NoOfCalories', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietrisk',
            name='noofpersons',
            field=models.CharField(blank=True, db_column='NoofPersons', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hormonalrisk',
            name='Calorierange',
            field=models.CharField(blank=True, db_column='Calorierange', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hormonalrisk',
            name='NoOfPersons',
            field=models.CharField(blank=True, db_column='Age', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hormonalrisk',
            name='firststandarddeviation',
            field=models.CharField(blank=True, db_column='FirstStandardDeviation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hormonalrisk',
            name='hormonalcomplicationscategory',
            field=models.CharField(blank=True, db_column='HormonalComplicationsCategory', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='physicalactivityrisk',
            name='thirdstandarddeviationscore',
            field=models.CharField(blank=True, db_column='thirdstandarddeviationscore', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sexrisk',
            name='thirdstandarddeviationscore',
            field=models.CharField(blank=True, db_column='thirdstandarddeviationscore', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dietrisk',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Female', max_length=20),
        ),
        migrations.AlterField(
            model_name='dietrisk',
            name='firststandarddeviationscore',
            field=models.CharField(blank=True, db_column='FirstStandardDeviationScore', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dietrisk',
            name='mean',
            field=models.CharField(blank=True, db_column='Mean', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dietrisk',
            name='secondstandarddeviation',
            field=models.CharField(blank=True, db_column='SecondStandardDeviation', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dietrisk',
            name='secondstandarddeviationscore',
            field=models.CharField(blank=True, db_column='SecondStandardDeviationScore', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dietrisk',
            name='thirdstandarddeviation',
            field=models.CharField(blank=True, db_column='ThirdStandardDeviation', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dietrisk',
            name='thirdstandarddeviationscore',
            field=models.CharField(blank=True, db_column='ThirdStandardDeviationScore', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hormonalrisk',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Same', 'Same')], default='Same', max_length=20),
        ),
        migrations.AlterField(
            model_name='hormonalrisk',
            name='firststandarddeviationscore',
            field=models.CharField(blank=True, db_column='FirstStandardDeviationScore', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hormonalrisk',
            name='mean',
            field=models.FloatField(blank=True, db_column='Mean', null=True),
        ),
        migrations.AlterField(
            model_name='hormonalrisk',
            name='secondstandarddeviation',
            field=models.CharField(blank=True, db_column='SecondStandardDeviation', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hormonalrisk',
            name='secondstandarddeviationscore',
            field=models.CharField(blank=True, db_column='SecondStandardDeviationScore', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hormonalrisk',
            name='thirdstandarddeviation',
            field=models.CharField(blank=True, db_column='ThirdStandardDeviation', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hormonalrisk',
            name='thirdstandarddeviationscore',
            field=models.CharField(blank=True, db_column='ThirdStandardDeviationScore', max_length=200, null=True),
        ),
    ]
