# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0008_auto_20160803_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalactivityrisk',
            name='agegroup',
        ),
        migrations.RemoveField(
            model_name='physicalactivityrisk',
            name='weightrange',
        ),
        migrations.AddField(
            model_name='physicalactivityrisk',
            name='Frequency',
            field=models.CharField(blank=True, db_column='Frequency', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physicalactivityrisk',
            name='TimePeriod',
            field=models.CharField(blank=True, db_column='TimePeriod', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='physicalactivityrisk',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Same', 'Same')], default='Female', max_length=20),
        ),
    ]
