# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0010_auto_20160803_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressurerisk',
            name='documentation',
            field=models.CharField(blank=True, db_column='Documentation', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='risklabels',
            name='documentation',
            field=models.CharField(blank=True, db_column='Documentation', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='documentation',
            field=models.CharField(blank=True, db_column='Documentation', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='smokingrisk',
            name='documentation',
            field=models.CharField(blank=True, db_column='Documentation', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='smokingrisk',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Same', 'Same')], default='Same', max_length=20),
        ),
    ]
