# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0011_auto_20160803_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sexrisk',
            name='agegroup',
        ),
        migrations.AddField(
            model_name='sexrisk',
            name='Frequency',
            field=models.CharField(blank=True, db_column='Frequency', max_length=200, null=True),
        ),
    ]
