# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0012_auto_20160803_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hormonalrisk',
            name='Calorierange',
        ),
        migrations.RemoveField(
            model_name='hormonalrisk',
            name='NoOfPersons',
        ),
        migrations.AddField(
            model_name='hormonalrisk',
            name='AgeRange',
            field=models.CharField(blank=True, db_column='AgeRange', max_length=300, null=True),
        ),
    ]
