# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0013_auto_20160803_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrisk',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Same', 'Same')], default='Female', max_length=20),
        ),
    ]
