# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0014_auto_20160803_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrisk',
            name='firststandarddeviation',
            field=models.CharField(blank=True, db_column='FirstStandardDeviation', max_length=300, null=True),
        ),
    ]
