# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0015_dietrisk_firststandarddeviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='smokingrisk',
            name='PercentageSmokerRange',
            field=models.CharField(blank=True, db_column='PercentageSmokerRange', max_length=300, null=True),
        ),
    ]
