# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0016_smokingrisk_percentagesmokerrange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cholesterol',
            options={'managed': True},
        ),
    ]
