# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0017_auto_20160803_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cholesterol',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Same', 'Same')], default='Male', max_length=20),
        ),
    ]
