# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhirfront', '0018_cholesterol_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cholesterol',
            new_name='CholesterolRisk',
        ),
        migrations.AlterModelTable(
            name='cholesterolrisk',
            table='CholesterolRisk',
        ),
    ]
