# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0006_auto_20160716_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhichDrink', models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20)),
                ('FatInTake', models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20)),
                ('FoodSupliment', models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CholesterolReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhichDrink', models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20)),
                ('FatInTake', models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20)),
                ('FoodSupliment', models.CharField(choices=[('Sugar Drinks per Day', [('No', 'No'), ('Negligible', 'Negligible')]), ('Alcohol Drinks per Day', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('Juices per Day', [('Natual', 'Natual'), ('Artifical Falavored', 'Artifical Falavored')]), ('Herbal Drinks', [('Rare', 'Rare'), ('Once', 'Once'), ('Twice', 'Twice'), ('Thrice', 'Thrice'), ('Thrice', 'Thrice'), ('More than 3 times', 'More than 3 times')]), ('WaterInTake', [('3 Glasses', '3 Glasses'), ('5 Glasses', '5 Glasses'), ('7 Glasses', '7 Glasses'), ('>7 Glasses', '>7 Glasses')]), ('XXX', [('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')])], default='Slow', max_length=20)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedicalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Nicotine Bubble Gum', max_length=100, verbose_name='Name')),
                ('Age', models.CharField(default='Nicotine Bubble Gum', max_length=100, verbose_name='Name')),
                ('Sex', models.CharField(default='Nicotine Bubble Gum', max_length=100, verbose_name='Name')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
