# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0007_bloodpressurereading_cholesterolreading_usermedicalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedicalprofile',
            name='FamilyHistory',
            field=models.CharField(default='Nicotine Bubble Gum', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='usermedicalprofile',
            name='Weight',
            field=models.CharField(default='Nicotine Bubble Gum', max_length=100, verbose_name='Name'),
        ),
    ]
