# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0009_auto_20160716_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedicalprofile',
            name='Age',
            field=models.CharField(default='20', max_length=100, verbose_name='Age :'),
        ),
        migrations.AlterField(
            model_name='usermedicalprofile',
            name='FamilyHistory',
            field=models.CharField(default=' ', max_length=100, verbose_name='Family History :'),
        ),
        migrations.AlterField(
            model_name='usermedicalprofile',
            name='HormonalFactor',
            field=models.CharField(default='X', max_length=100, verbose_name='Hormonal Factor(s)'),
        ),
        migrations.AlterField(
            model_name='usermedicalprofile',
            name='Name',
            field=models.CharField(default='Shubham', max_length=100, verbose_name='Full Name:'),
        ),
        migrations.AlterField(
            model_name='usermedicalprofile',
            name='Sex',
            field=models.CharField(default='Male', max_length=100, verbose_name='Sex: '),
        ),
        migrations.AlterField(
            model_name='usermedicalprofile',
            name='Weight',
            field=models.IntegerField(default='50', max_length=100, verbose_name='Weight in Kgs'),
        ),
    ]
