# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fhiradmin', '0012_auto_20160717_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cholesterolreading',
            name='FatInTake',
        ),
        migrations.RemoveField(
            model_name='cholesterolreading',
            name='FoodSupliment',
        ),
        migrations.RemoveField(
            model_name='cholesterolreading',
            name='WhichDrink',
        ),
        migrations.RemoveField(
            model_name='usermedicalprofile',
            name='Name',
        ),
        migrations.AddField(
            model_name='cholesterolreading',
            name='HighDensityLipoProtein',
            field=models.IntegerField(default='90', verbose_name='H D L '),
        ),
        migrations.AddField(
            model_name='cholesterolreading',
            name='LastDateOfTest',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 7, 8, 36, 519000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cholesterolreading',
            name='LowDensityLipoProtein',
            field=models.IntegerField(default='90', verbose_name='L D L '),
        ),
        migrations.AddField(
            model_name='cholesterolreading',
            name='TotalCholesterol',
            field=models.IntegerField(default='90', verbose_name='Total Cholesterol'),
        ),
        migrations.AddField(
            model_name='cholesterolreading',
            name='TriglyceridesReadings',
            field=models.IntegerField(default='90', verbose_name='Triglycerides'),
        ),
        migrations.AddField(
            model_name='cholesterolreading',
            name='VeryLowDensityLipoProtein',
            field=models.IntegerField(default='90', verbose_name='VLDL'),
        ),
        migrations.AddField(
            model_name='usermedicalprofile',
            name='FullName',
            field=models.CharField(default='Shubham Sharma', max_length=100, verbose_name='Full Name:'),
        ),
        migrations.AlterField(
            model_name='bloodpressurereading',
            name='DiastolicReading',
            field=models.IntegerField(default='100', verbose_name='Diastolic   Reading'),
        ),
    ]
